mac:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Mac/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin

clean:
	rm -vf bin/com/districtap/pengbot/*.class bin/org/eclipse/wb/swt*.class
