mac:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Mac/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin
linux:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Linux/swt-4.4.2-gtk-linux-x86/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin
linux64:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Linux/swt-4.4.2-gtk-linux-x86_64/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin
windows:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Windows/32bit/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin
windows64:
	javac -cp lib/pircbot.jar:lib/swing2swt.jar:lib/SWT/Windows/64bit/swt.jar:. src/org/eclipse/wb/swt/SWTResourceManager.java src/com/districtap/pengbot/*.java -d bin
clean:
	rm -vf bin/com/districtap/pengbot/*.class bin/org/eclipse/wb/swt*.class
